services:
  postgres:
    image: postgres:16
    container_name: handihand-dev
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: handihand_dev
    ports:
      - "8888:5432"

  db-migration:
    image: amacneil/dbmate:2
    entrypoint: ["/bin/sh", "-c", "dbmate wait && dbmate migrate"]
    volumes:
      - "./db:/db"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@handihand-dev:5432/handihand_dev?sslmode=disable
