INSERT INTO public.tag (word) VALUES
	 ('Embroidery'),
	 ('Felting'),
	 ('Doll Making'),
	 ('Basket Weaving'),
	 ('Candle Making'),
	 ('Ceramics'),
	 ('Crochet'),
	 ('Decoupage'),
	 ('Ikebana'),
	 ('Lace Making'),
	 ('Latch Hook Rugs'),
	 ('Leatherwork'),
	 ('Macrame'),
	 ('Make Miniature Models'),
	 ('Make Beaded Jewelry'),
	 ('Mosaics'),
	 ('Origami'),
	 ('Paper Making'),
	 ('Quilting'),
	 ('Soap Making'),
	 ('Stained Glass'),
	 ('Weaving'),
	 ('Printmaking'),
	 ('Wood Carving'),
	 ('Knitting');
